"""Донаты

Revision ID: b86548e102c6
Revises: 10ff371d106f
Create Date: 2023-07-21 11:56:23.863850

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b86548e102c6"
down_revision = "10ff371d106f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "donation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("full_amount", sa.Integer(), nullable=True),
        sa.Column("invested_amount", sa.Integer(), nullable=True),
        sa.Column("fully_invested", sa.Boolean(), nullable=True),
        sa.Column("create_date", sa.DateTime(), nullable=True),
        sa.Column("close_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("donation")
    # ### end Alembic commands ###
